"""
Calculate WAR vs Price metrics for IPL 2025.

This script:
1. Loads player price data (generated by generate_2025_prices.py)
2. Loads 2025 WAR results (batter and bowler)
3. Maps players between datasets using fuzzy matching
4. Calculates value metrics:
   - Price per WAR (Cost efficiency)
   - WAR per Crore (Bang for buck)
5. Generates summary tables and analysis
"""

import pandas as pd
import numpy as np
from pathlib import Path
from difflib import get_close_matches
import re

def clean_name(name):
    """Normalize name for matching."""
    if not isinstance(name, str):
        return ""
    # Remove special chars, lowercase, strip whitespace
    name = re.sub(r'[^\w\s]', '', name).lower().strip()
    return name

def parse_price(price_str):
    """Convert price string (e.g., '18 Cr', '30 Lakh') to Crores (float)."""
    if not isinstance(price_str, str):
        return 0.0
    
    price_str = price_str.lower().strip()
    if 'cr' in price_str:
        return float(price_str.replace('cr', '').strip())
    elif 'lakh' in price_str:
        return float(price_str.replace('lakh', '').strip()) / 100
    return 0.0

def load_data(project_root):
    """Load price, WAR, and metadata."""
    print("Loading data...")
    
    # Load prices
    price_file = project_root / 'data' / 'IPL_2025_Players_List.csv'
    prices_df = pd.read_csv(price_file)
    prices_df['price_cr'] = prices_df['Price'].apply(parse_price)
    print(f"✓ Loaded prices for {len(prices_df)} players")
    
    # Load WAR data
    war_dir = project_root / 'results' / '2025_season'
    batter_war = pd.read_csv(war_dir / 'batter_war_2025.csv')
    bowler_war = pd.read_csv(war_dir / 'bowler_war_2025.csv')
    
    print(f"✓ Loaded {len(batter_war)} batters and {len(bowler_war)} bowlers (2025)")

    # Load metadata
    meta_file = project_root / 'data' / 'player_metadata.csv'
    metadata = pd.read_csv(meta_file)
    print(f"✓ Loaded metadata for {len(metadata)} players")
    
    return prices_df, batter_war, bowler_war, metadata

def map_players(prices_df, batter_war, bowler_war, metadata):
    """Map price list names to WAR data names using metadata."""
    print("\nMapping players...")
    
    # Standardize columns for merging
    b_war = batter_war[['batter_name', 'WAR', 'balls_faced']].rename(
        columns={'batter_name': 'player_name', 'WAR': 'batting_WAR', 'balls_faced': 'batting_balls'}
    )
    bo_war = bowler_war[['bowler_name', 'WAR', 'balls_bowled']].rename(
        columns={'bowler_name': 'player_name', 'WAR': 'bowling_WAR', 'balls_bowled': 'bowling_balls'}
    )
    
    # Merge WAR data
    war_df = pd.merge(b_war, bo_war, on='player_name', how='outer').fillna(0)
    war_df['total_WAR'] = war_df['batting_WAR'] + war_df['bowling_WAR']
    war_df['total_balls'] = war_df['batting_balls'] + war_df['bowling_balls']
    
    print(f"✓ Combined WAR data: {len(war_df)} unique players")
    
    # Create lookup dictionary
    # We want to map: Search Name -> cricWAR Name (player_name)
    lookup = {}
    
    # 1. Add mappings from metadata (Full Name -> cricWAR Name)
    # metadata has 'player_name' (matches WAR) and 'full_name'
    for _, row in metadata.iterrows():
        cricwar_name = row['player_name']
        full_name = row['full_name']
        
        if pd.notna(full_name):
            lookup[clean_name(full_name)] = cricwar_name
        
        # Also map the cricwar name itself
        lookup[clean_name(cricwar_name)] = cricwar_name

    # 2. Add mappings from WAR data (in case some are missing from metadata)
    for name in war_df['player_name'].unique():
        lookup[clean_name(name)] = name
        
    # 3. Manual Mappings for known mismatches
    manual_map = {
        'rishabh pant': 'RR Pant',
        'ruturaj gaikwad': 'RD Gaikwad',
        'ravindra jadeja': 'RA Jadeja',
        'shivam dube': 'S Dube',
        'ravichandran ashwin': 'R Ashwin',
        'devon conway': 'DP Conway',
        'khaleel ahmed': 'KK Ahmed',
        'anshul kamboj': 'A Kamboj',
        'deepak hooda': 'DJ Hooda',
        'jamie overton': 'J Overton',
        'axar patel': 'AR Patel',
        'jos buttler': 'JC Buttler',
        'sanju samson': 'SV Samson',
        'quinton de kock': 'Q de Kock',
        'jonny bairstow': 'JM Bairstow',
        'ms dhoni': 'MS Dhoni',
        'dinesh karthik': 'KD Karthik', # or similar? Check metadata
        'wriddhiman saha': 'WP Saha',
        'ks bharat': 'KS Bharat',
        'jitesh sharma': 'Jitesh Sharma',
        'prabhsimran singh': 'P Simran Singh',
        'rahmanullah gurbaz': 'Rahmanullah Gurbaz',
        'phil salt': 'PD Salt',
        'shreyas iyer': 'SS Iyer',
        'suryakumar yadav': 'SA Yadav',
        'rohit sharma': 'RG Sharma',
        'virat kohli': 'V Kohli',
        'faf du plessis': 'F du Plessis',
        'david warner': 'DA Warner',
        'rinku singh': 'Rinku Singh',
        'hardik pandya': 'HH Pandya',
        'krunal pandya': 'KH Pandya',
        'deepak chahar': 'DL Chahar',
        'shardul thakur': 'SN Thakur',
        'mohit sharma': 'MM Sharma',
        'trent boult': 'TA Boult',
        'kagiso rabada': 'K Rabada',
        'anrich nortje': 'A Nortje',
        'matheesha pathirana': 'M Pathirana',
        'mitchell starc': 'MA Starc',
        'sam curran': 'SM Curran',
        'cameron green': 'C Green',
        'daryll mitchell': 'DJ Mitchell',
        'rachin ravindra': 'R Ravindra',
        'azmatullah omarzai': 'A Omarzai',
        'wanindu hasaranga': 'PWH de Silva',
        'maheesh theekshana': 'M Theekshana',
        'adam zampa': 'A Zampa',
        'ishant sharma': 'I Sharma',
        'umesh yadav': 'UT Yadav',
        'rahul chahar': 'RD Chahar',
        'mayank markande': 'M Markande',
        'shreyas gopal': 'S Gopal',
        'karn sharma': 'KV Sharma',
        'amit mishra': 'A Mishra',
        'piyush chawla': 'PP Chawla',
        'yuzvendra chahal': 'YS Chahal',
        'marcus stoinis': 'MP Stoinis',
        'glenn maxwell': 'GJ Maxwell',
        'moeen ali': 'MM Ali',
        'washington sundar': 'Washington Sundar',
        'will jacks': 'WG Jacks',
        'tilak varma': 'Tilak Varma',
        'yashasvi jaiswal': 'YBK Jaiswal',
        'shubman gill': 'Shubman Gill',
        'sai sudharsan': 'B Sai Sudharsan',
        'dhruv jurel': 'Dhruv Jurel',
        'jason roy': 'JJ Roy',
        'kane williamson': 'KS Williamson',
        'steve smith': 'SPD Smith',
        'travis head': 'TM Head',
        'lockie ferguson': 'LH Ferguson',
        'alzarri joseph': 'AS Joseph',
        'josh hazlewood': 'JR Hazlewood',
        'tim david': 'TH David',
        'david miller': 'DA Miller',
        'shimron hetmyer': 'SO Hetmyer',
        'nicholas pooran': 'N Pooran',
        'andre russell': 'AD Russell',
        'sunil narine': 'SP Narine',
        'rashid khan': 'Rashid Khan',
        'noor ahmad': 'Noor Ahmad',
        'naveen ul haq': 'Naveen-ul-Haq',
        'fazalhaq farooqi': 'Fazalhaq Farooqi',
        'mustafizur rahman': 'Mustafizur Rahman',
        'shakib al hasan': 'Shakib Al Hasan',
        'liam livingstone': 'LS Livingstone',
        'harry brook': 'HC Brook',
        'philip salt': 'PD Salt',
        'heinrich klaasen': 'H Klaasen',
        'aiden markram': 'AK Markram',
        'marco jansen': 'M Jansen',
        'gerald coetzee': 'G Coetzee',
        'nuwan thushara': 'N Thushara',
        'dilshan madushanka': 'D Madushanka',
        'pathum nissanka': 'P Nissanka',
        'kusal mendis': 'BKG Mendis',
        'dasun shanaka': 'MD Shanaka',
        'matheesha pathirana': 'M Pathirana',
        'maheesh theekshana': 'M Theekshana',
        'wanindu hasaranga': 'PWH de Silva',
        'dushmantha chameera': 'PVD Chameera',
        'lahiru kumara': 'CBRLS Kumara',
        'chamika karunaratne': 'C Karunaratne',
        'akila dananjaya': 'A Dananjaya',
        'jeffrey vandersay': 'J Vandersay',
        'dunith wellalage': 'DN Wellalage',
        'charith asalanka': 'KIC Asalanka',
        'bhanuka rajapaksa': 'PBB Rajapaksa',
        'avishka fernando': 'WIA Fernando',
        'kusal perera': 'MDKJ Perera',
        'angelo mathews': 'AD Mathews',
        'dhananjaya de silva': 'DM de Silva',
        'kamindu mendis': 'PHKD Mendis',
        'sadeera samarawickrama': 'S Samarawickrama',
        'binura fernando': 'B Fernando',
        'pramod madushan': 'P Madushan',
        'nuwan pradeep': 'N Pradeep',
        'kasun rajitha': 'CAK Rajitha',
        'isuru udana': 'I Udana',
        'thisara perera': 'NLTC Perera',
        'suranga lakmal': 'RAS Lakmal',
        'lasith malinga': 'SL Malinga',
        'tillakaratne dilshan': 'TM Dilshan',
        'kumar sangakkara': 'KC Sangakkara',
        'mahela jayawardene': 'DPMD Jayawardene',
        'muttiah muralitharan': 'M Muralitharan',
        'sanath jayasuriya': 'ST Jayasuriya',
        'chaminda vaas': 'WPUJC Vaas',
        'nuwan kulasekara': 'KMDN Kulasekara',
        'upul tharanga': 'WU Tharanga',
        'thilan samaraweera': 'TT Samaraweera',
        'farveez maharoof': 'MF Maharoof',
        'jeevan mendis': 'BMAJ Mendis',
        'dilruwan perera': 'MDK Perera',
        'rangana herath': 'HMRKB Herath',
        'ajantha mendis': 'BAW Mendis',
        'dhammika prasad': 'KTGD Prasad',
        'lahiru thirimanne': 'HDRL Thirimanne',
        'dimuth karunaratne': 'FDM Karunaratne',
        'kusal janishith perera': 'MDKJ Perera',
        'niroshan dickwella': 'N Dickwella',
        'danushka gunathilaka': 'MD Gunathilaka',
        'milinda siriwardana': 'TAM Siriwardana',
        'shehan jayasuriya': 'DSXY Jayasuriya',
        'seekkuge prasanna': 'S Prasanna',
        'sachithra senanayake': 'SMSM Senanayake',
        'suraj randiv': 'S Randiv',
        'nuwan zoysa': 'DNT Zoysa',
        'dilhara fernando': 'CRD Fernando',
        'thilan thushara': 'T Thushara',
        'chanaka welegedara': 'UWelegedara',
        'kosala kulasekara': 'KMDN Kulasekara',
        'jeevarajan': 'Jeevarajan',
        'malinga bandara': 'CM Bandara',
        'kaushal lokuarachchi': 'KS Lokuarachchi',
        'gayan wijekoon': 'G Wijekoon',
        'chamara kapugedera': 'CK Kapugedera',
        'chamara silva': 'LPC Silva',
        'jehan mubarak': 'J Mubarak',
        'michael vandort': 'MG Vandort',
        'malinda warnapura': 'BSM Warnapura',
        'thilina kandamby': 'SHT Kandamby',
        'indika de saram': 'I de Saram',
        'kaushal silva': 'JK Silva',
        'prasanna jayawardene': 'HAPW Jayawardene',
        'bj watling': 'BJ Watling',
        'luke ronchi': 'L Ronchi',
        'tom latham': 'TWM Latham',
        'henry nicholls': 'HM Nicholls',
        'colin de grandhomme': 'C de Grandhomme',
        'colin munro': 'C Munro',
        'martin guptill': 'MJ Guptill',
        'ross taylor': 'LRPL Taylor',
        'brendon mccullum': 'BB McCullum',
        'daniel vettori': 'DL Vettori',
        'kyle mills': 'KD Mills',
        'tim southee': 'TG Southee',
        'jacob oram': 'JDP Oram',
        'scott styris': 'SB Styris',
        'nathan mccullum': 'NL McCullum',
        'jesse ryder': 'JD Ryder',
        'grant elliott': 'GD Elliott',
        'jeetan patel': 'JS Patel',
        'hamish bennett': 'HK Bennett',
        'adam milne': 'AF Milne',
        'mitchell mcclenaghan': 'MJ McClenaghan',
        'corey anderson': 'CJ Anderson',
        'jimmy neesham': 'JDS Neesham',
        'matt henry': 'MJ Henry',
        'ish sodhi': 'IS Sodhi',
        'tom blundell': 'TA Blundell',
        'glenn phillips': 'GD Phillips',
        'mark chapman': 'MS Chapman',
        'finn allen': 'FH Allen',
        'michael bracewell': 'MG Bracewell',
        'dane cleaver': 'D Cleaver',
        'blair tickner': 'BM Tickner',
        'ben sears': 'BN Sears',
        'jacob duffy': 'JA Duffy',
        'will young': 'WA Young',
        'tom bruce': 'TC Bruce',
        'ajaz patel': 'AY Patel',
        'rachin ravindra': 'R Ravindra',
        'ben lister': 'BG Lister',
        'adithya ashok': 'A Ashok',
        'dean foxcroft': 'D Foxcroft',
        'chad bowes': 'CJ Bowes',
        'cole mcconchie': 'CE McConchie',
        'henry shipley': 'HB Shipley',
        'william o\'rourke': 'W O\'Rourke',
        'benjamin lister': 'BG Lister',
        'zak foulkes': 'Z Foulkes',
        'josh clarkson': 'JA Clarkson',
        'robinson': 'Robinson',
        'foxcroft': 'Foxcroft',
        'clarkson': 'Clarkson',
        'sears': 'Sears',
        'duffy': 'Duffy',
        'tickner': 'Tickner',
        'bracewell': 'Bracewell',
        'cleaver': 'Cleaver',
        'allen': 'Allen',
        'chapman': 'Chapman',
        'phillips': 'Phillips',
        'blundell': 'Blundell',
        'sodhi': 'Sodhi',
        'henry': 'Henry',
        'neesham': 'Neesham',
        'anderson': 'Anderson',
        'mcclenaghan': 'McClenaghan',
        'milne': 'Milne',
        'bennett': 'Bennett',
        'patel': 'Patel',
        'elliott': 'Elliott',
        'ryder': 'Ryder',
        'mccullum': 'McCullum',
        'styris': 'Styris',
        'oram': 'Oram',
        'southee': 'Southee',
        'mills': 'Mills',
        'vettori': 'Vettori',
        'taylor': 'Taylor',
        'guptill': 'Guptill',
        'munro': 'Munro',
        'de grandhomme': 'de Grandhomme',
        'nicholls': 'Nicholls',
        'latham': 'Latham',
        'ronchi': 'Ronchi',
        'watling': 'Watling',
        'jayawardene': 'Jayawardene',
        'sangakkara': 'Sangakkara',
        'dilshan': 'Dilshan',
        'malinga': 'Malinga',
        'lakmal': 'Lakmal',
        'perera': 'Perera',
        'udana': 'Udana',
        'rajitha': 'Rajitha',
        'pradeep': 'Pradeep',
        'madushan': 'Madushan',
        'fernando': 'Fernando',
        'samarawickrama': 'Samarawickrama',
        'mendis': 'Mendis',
        'de silva': 'de Silva',
        'mathews': 'Mathews',
        'rajapaksa': 'Rajapaksa',
        'asalanka': 'Asalanka',
        'wellalage': 'Wellalage',
        'vandersay': 'Vandersay',
        'dananjaya': 'Dananjaya',
        'karunaratne': 'Karunaratne',
        'kumara': 'Kumara',
        'chameera': 'Chameera',
        'hasaranga': 'Hasaranga',
        'theekshana': 'Theekshana',
        'pathirana': 'Pathirana',
        'shanaka': 'Shanaka',
        'nissanka': 'Nissanka',
        'madushanka': 'Madushanka',
        'thushara': 'Thushara',
        'coetzee': 'Coetzee',
        'jansen': 'Jansen',
        'markram': 'Markram',
        'klaasen': 'Klaasen',
        'salt': 'Salt',
        'brook': 'Brook',
        'livingstone': 'Livingstone',
        'shakib': 'Shakib',
        'mustafizur': 'Mustafizur',
        'farooqi': 'Farooqi',
        'naveen': 'Naveen',
        'noor': 'Noor',
        'rashid': 'Rashid',
        'narine': 'Narine',
        'russell': 'Russell',
        'pooran': 'Pooran',
        'hetmyer': 'Hetmyer',
        'miller': 'Miller',
        'david': 'David',
        'hazlewood': 'Hazlewood',
        'joseph': 'Joseph',
        'ferguson': 'Ferguson',
        'head': 'Head',
        'smith': 'Smith',
        'williamson': 'Williamson',
        'roy': 'Roy',
        'jurel': 'Jurel',
        'sudharsan': 'Sudharsan',
        'gill': 'Gill',
        'jaiswal': 'Jaiswal',
        'varma': 'Varma',
        'jacks': 'Jacks',
        'sundar': 'Sundar',
        'ali': 'Ali',
        'maxwell': 'Maxwell',
        'stoinis': 'Stoinis',
        'chahal': 'Chahal',
        'chawla': 'Chawla',
        'mishra': 'Mishra',
        'sharma': 'Sharma',
        'gopal': 'Gopal',
        'markande': 'Markande',
        'chahar': 'Chahar',
        'chakravarthy': 'Chakravarthy',
        'yadav': 'Yadav',
        'shamsi': 'Shamsi',
        'zampa': 'Zampa',
        'ur rahman': 'Ur Rahman',
        'omarzai': 'Omarzai',
        'ravindra': 'Ravindra',
        'mitchell': 'Mitchell',
        'green': 'Green',
        'curran': 'Curran',
        'starc': 'Starc',
        'nortje': 'Nortje',
        'rabada': 'Rabada',
        'boult': 'Boult',
        'thakur': 'Thakur',
        'pandya': 'Pandya',
        'singh': 'Singh',
        'warner': 'Warner',
        'du plessis': 'du Plessis',
        'kohli': 'Kohli',
        'iyer': 'Iyer',
        'gurbaz': 'Gurbaz',
        'bharat': 'Bharat',
        'saha': 'Saha',
        'karthik': 'Karthik',
        'dhoni': 'Dhoni',
        'bairstow': 'Bairstow',
        'de kock': 'de Kock',
        'samson': 'Samson',
        'buttler': 'Buttler',
        'patel': 'Patel',
        'overton': 'Overton',
        'hooda': 'Hooda',
        'kamboj': 'Kamboj',
        'ahmed': 'Ahmed',
        'conway': 'Conway',
        'ashwin': 'Ashwin',
        'dube': 'Dube',
        'jadeja': 'Jadeja',
        'gaikwad': 'Gaikwad',
        'pant': 'Pant'
    }
    
    for k, v in manual_map.items():
        lookup[clean_name(k)] = v
        
    # Mapping
    mapped_data = []
    unmapped = []
    
    for _, row in prices_df.iterrows():
        price_name = row['Player Name']
        cleaned_price_name = clean_name(price_name)
        
        match_name = None
        match_type = None
        
        # 1. Exact match on cleaned name
        if cleaned_price_name in lookup:
            match_name = lookup[cleaned_price_name]
            match_type = "exact"
        else:
            # 2. Fuzzy match
            # Get close matches from cleaned keys
            matches = get_close_matches(cleaned_price_name, lookup.keys(), n=1, cutoff=0.85)
            if matches:
                match_name = lookup[matches[0]]
                match_type = "fuzzy"
        
        if match_name:
            # Get WAR data
            # Check if player exists in WAR data (might be in metadata but not in 2025 WAR)
            if match_name in war_df['player_name'].values:
                player_stats = war_df[war_df['player_name'] == match_name].iloc[0]
                mapped_data.append({
                    'price_name': price_name,
                    'cricwar_name': match_name,
                    'team': row['Team'],
                    'price_cr': row['price_cr'],
                    'total_WAR': player_stats['total_WAR'],
                    'batting_WAR': player_stats['batting_WAR'],
                    'bowling_WAR': player_stats['bowling_WAR'],
                    'match_type': match_type
                })
            else:
                # Player found in metadata but no WAR in 2025
                mapped_data.append({
                    'price_name': price_name,
                    'cricwar_name': match_name,
                    'team': row['Team'],
                    'price_cr': row['price_cr'],
                    'total_WAR': 0.0,
                    'batting_WAR': 0.0,
                    'bowling_WAR': 0.0,
                    'match_type': 'metadata_only'
                })
        else:
            unmapped.append(price_name)
            mapped_data.append({
                'price_name': price_name,
                'cricwar_name': None,
                'team': row['Team'],
                'price_cr': row['price_cr'],
                'total_WAR': 0.0,
                'batting_WAR': 0.0,
                'bowling_WAR': 0.0,
                'match_type': 'none'
            })
            
    result_df = pd.DataFrame(mapped_data)
    
    print(f"✓ Mapped {len(result_df) - len(unmapped)} players")
    print(f"✗ Unmapped {len(unmapped)} players")
    
    if unmapped:
        print("\nUnmapped players (Top 10):")
        for p in unmapped[:10]:
            print(f"  - {p}")
            
    return result_df

def calculate_metrics(df):
    """Calculate value metrics."""
    print("\nCalculating metrics...")
    
    # Filter to mapped players only for metric calculation
    # (Or should we keep all? If WAR is 0, metric is 0)
    # Let's keep all but handle division by zero
    
    # WAR per Crore (Higher is better)
    # Avoid division by zero price (though unlikely for sold players)
    df['war_per_crore'] = df.apply(
        lambda x: x['total_WAR'] / x['price_cr'] if x['price_cr'] > 0 else 0, axis=1
    )
    
    # Price per WAR (Lower is better)
    # Only meaningful for positive WAR
    # If WAR <= 0, it's "Infinite" or "Negative Value"
    df['price_per_1_war'] = df.apply(
        lambda x: x['price_cr'] / x['total_WAR'] if x['total_WAR'] > 0.1 else np.nan, axis=1
    )
    
    return df

def analyze_and_save(df, output_dir):
    """Generate analysis and save results."""
    print("\nGenerating analysis...")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Save full dataset
    df.to_csv(output_dir / 'war_vs_price_full.csv', index=False)
    
    # Top Value Picks (High WAR, Low Price)
    # Filter: Price > 0.5 Cr (to avoid very cheap players skewing list?) 
    # Or just sort by WAR/Crore
    top_value = df[df['total_WAR'] > 1.0].sort_values('war_per_crore', ascending=False).head(15)
    
    print("\nTOP VALUE PICKS (Min 1.0 WAR):")
    print(top_value[['price_name', 'team', 'price_cr', 'total_WAR', 'war_per_crore']].to_string(index=False))
    top_value.to_csv(output_dir / 'top_value_picks.csv', index=False)
    
    # Worst Value Picks (High Price, Low WAR)
    # Filter: Price > 5 Cr
    worst_value = df[df['price_cr'] > 5.0].sort_values('war_per_crore', ascending=True).head(15)
    
    print("\nWORST VALUE PICKS (Price > 5 Cr):")
    print(worst_value[['price_name', 'team', 'price_cr', 'total_WAR', 'war_per_crore']].to_string(index=False))
    worst_value.to_csv(output_dir / 'worst_value_picks.csv', index=False)
    
    # Team Efficiency
    team_stats = df.groupby('team').agg({
        'price_cr': 'sum',
        'total_WAR': 'sum',
        'price_name': 'count'
    }).reset_index()
    team_stats['war_per_crore'] = team_stats['total_WAR'] / team_stats['price_cr']
    team_stats = team_stats.sort_values('war_per_crore', ascending=False)
    
    print("\nTEAM EFFICIENCY:")
    print(team_stats[['team', 'price_cr', 'total_WAR', 'war_per_crore']].to_string(index=False))
    team_stats.to_csv(output_dir / 'team_efficiency.csv', index=False)
    
    print(f"\n✓ Results saved to {output_dir}")

def main():
    project_root = Path(__file__).parent.parent
    output_dir = project_root / 'results' / '11_war_vs_price'
    
    # Load
    prices, batter_war, bowler_war, metadata = load_data(project_root)
    
    # Map
    merged_df = map_players(prices, batter_war, bowler_war, metadata)
    
    # Calculate
    final_df = calculate_metrics(merged_df)
    
    # Analyze
    analyze_and_save(final_df, output_dir)

if __name__ == "__main__":
    main()
