import pandas as pd
from pathlib import Path

def main():
    data = [
        # Chennai Super Kings (CSK)
        ("Chennai Super Kings", "Ruturaj Gaikwad", "18 Cr"),
        ("Chennai Super Kings", "Ravindra Jadeja", "18 Cr"),
        ("Chennai Super Kings", "Matheesha Pathirana", "13 Cr"),
        ("Chennai Super Kings", "Shivam Dube", "12 Cr"),
        ("Chennai Super Kings", "MS Dhoni", "4 Cr"),
        ("Chennai Super Kings", "Ravichandran Ashwin", "9.75 Cr"),
        ("Chennai Super Kings", "Noor Ahmad", "10 Cr"),
        ("Chennai Super Kings", "Devon Conway", "6.25 Cr"),
        ("Chennai Super Kings", "Khaleel Ahmed", "4.80 Cr"),
        ("Chennai Super Kings", "Rachin Ravindra", "4 Cr"),
        ("Chennai Super Kings", "Anshul Kamboj", "3.40 Cr"),
        ("Chennai Super Kings", "Rahul Tripathi", "3.40 Cr"),
        ("Chennai Super Kings", "Sam Curran", "2.40 Cr"),
        ("Chennai Super Kings", "Gurjapneet Singh", "2.20 Cr"),
        ("Chennai Super Kings", "Nathan Ellis", "2 Cr"),
        ("Chennai Super Kings", "Deepak Hooda", "1.70 Cr"),
        ("Chennai Super Kings", "Jamie Overton", "1.50 Cr"),
        ("Chennai Super Kings", "Vijay Shankar", "1.20 Cr"),
        ("Chennai Super Kings", "Mukesh Choudhary", "30 Lakh"),
        ("Chennai Super Kings", "Shaik Rasheed", "30 Lakh"),
        ("Chennai Super Kings", "Kamlesh Nagarkoti", "30 Lakh"),
        ("Chennai Super Kings", "Ramakrishna Ghosh", "30 Lakh"),
        ("Chennai Super Kings", "Shreyas Gopal", "30 Lakh"),
        ("Chennai Super Kings", "Vansh Bedi", "30 Lakh"),
        ("Chennai Super Kings", "Andre Siddarth", "30 Lakh"),

        # Delhi Capitals (DC)
        ("Delhi Capitals", "Axar Patel", "16.50 Cr"),
        ("Delhi Capitals", "Kuldeep Yadav", "13.25 Cr"),
        ("Delhi Capitals", "Tristan Stubbs", "10 Cr"),
        ("Delhi Capitals", "Abishek Porel", "4 Cr"),
        ("Delhi Capitals", "KL Rahul", "14 Cr"),
        ("Delhi Capitals", "Mitchell Starc", "11.75 Cr"),
        ("Delhi Capitals", "T Natarajan", "10.75 Cr"),
        ("Delhi Capitals", "Jake Fraser-McGurk", "9 Cr"),
        ("Delhi Capitals", "Mukesh Kumar", "8 Cr"),
        ("Delhi Capitals", "Harry Brook", "6.25 Cr"),
        ("Delhi Capitals", "Ashutosh Sharma", "3.80 Cr"),
        ("Delhi Capitals", "Mohit Sharma", "2.20 Cr"),
        ("Delhi Capitals", "Faf du Plessis", "2 Cr"),
        ("Delhi Capitals", "Sameer Rizvi", "95 Lakh"),
        ("Delhi Capitals", "Dushmantha Chameera", "75 Lakh"),
        ("Delhi Capitals", "Donovan Ferreira", "75 Lakh"),
        ("Delhi Capitals", "Karun Nair", "50 Lakh"),
        ("Delhi Capitals", "Vipraj Nigam", "50 Lakh"),
        ("Delhi Capitals", "Darshan Nalkande", "30 Lakh"),
        ("Delhi Capitals", "Ajay Mandal", "30 Lakh"),
        ("Delhi Capitals", "Manvanth Kumar", "30 Lakh"),
        ("Delhi Capitals", "Tripurana Vijay", "30 Lakh"),
        ("Delhi Capitals", "Madhav Tiwari", "30 Lakh"),
        ("Delhi Capitals", "Yuvraj Chaudhary", "30 Lakh"),

        # Gujarat Titans (GT)
        ("Gujarat Titans", "Rashid Khan", "18 Cr"),
        ("Gujarat Titans", "Shubman Gill", "16.50 Cr"),
        ("Gujarat Titans", "Sai Sudharsan", "8.50 Cr"),
        ("Gujarat Titans", "Rahul Tewatia", "4 Cr"),
        ("Gujarat Titans", "Shahrukh Khan", "4 Cr"),
        ("Gujarat Titans", "Jos Buttler", "15.75 Cr"),
        ("Gujarat Titans", "Mohammed Siraj", "12.25 Cr"),
        ("Gujarat Titans", "Kagiso Rabada", "10.75 Cr"),
        ("Gujarat Titans", "Prasidh Krishna", "9.50 Cr"),
        ("Gujarat Titans", "Mahipal Lomror", "1.70 Cr"),
        ("Gujarat Titans", "Sherfane Rutherford", "2.60 Cr"),
        ("Gujarat Titans", "Gerald Coetzee", "2.40 Cr"),
        ("Gujarat Titans", "Washington Sundar", "3.20 Cr"),
        ("Gujarat Titans", "Arshad Khan", "1.30 Cr"),
        ("Gujarat Titans", "Gurnoor Brar", "1.30 Cr"),
        ("Gujarat Titans", "Glenn Phillips", "2 Cr"),
        ("Gujarat Titans", "Ishant Sharma", "75 Lakh"),
        ("Gujarat Titans", "Jayant Yadav", "75 Lakh"),
        ("Gujarat Titans", "Karim Janat", "75 Lakh"),
        ("Gujarat Titans", "Kumar Kushagra", "65 Lakh"),
        ("Gujarat Titans", "Anuj Rawat", "30 Lakh"),
        ("Gujarat Titans", "Nishant Sindhu", "30 Lakh"),
        ("Gujarat Titans", "Manav Suthar", "30 Lakh"),
        ("Gujarat Titans", "Sai Kishore", "2 Cr"),
        ("Gujarat Titans", "Kulwant Khejroliya", "30 Lakh"),

        # Kolkata Knight Riders (KKR)
        ("Kolkata Knight Riders", "Rinku Singh", "13 Cr"),
        ("Kolkata Knight Riders", "Varun Chakaravarthy", "12 Cr"),
        ("Kolkata Knight Riders", "Sunil Narine", "12 Cr"),
        ("Kolkata Knight Riders", "Andre Russell", "12 Cr"),
        ("Kolkata Knight Riders", "Harshit Rana", "4 Cr"),
        ("Kolkata Knight Riders", "Ramandeep Singh", "4 Cr"),
        ("Kolkata Knight Riders", "Venkatesh Iyer", "23.75 Cr"),
        ("Kolkata Knight Riders", "Anrich Nortje", "6.50 Cr"),
        ("Kolkata Knight Riders", "Quinton de Kock", "3.60 Cr"),
        ("Kolkata Knight Riders", "Angkrish Raghuvanshi", "3 Cr"),
        ("Kolkata Knight Riders", "Spencer Johnson", "2.80 Cr"),
        ("Kolkata Knight Riders", "Rahmanullah Gurbaz", "2 Cr"),
        ("Kolkata Knight Riders", "Moeen Ali", "2 Cr"),
        ("Kolkata Knight Riders", "Vaibhav Arora", "1.80 Cr"),
        ("Kolkata Knight Riders", "Rovman Powell", "1.50 Cr"),
        ("Kolkata Knight Riders", "Ajinkya Rahane", "1.50 Cr"),
        ("Kolkata Knight Riders", "Manish Pandey", "75 Lakh"),
        ("Kolkata Knight Riders", "Umran Malik", "75 Lakh"),
        ("Kolkata Knight Riders", "Anukul Roy", "40 Lakh"),
        ("Kolkata Knight Riders", "Mayank Markande", "30 Lakh"),
        ("Kolkata Knight Riders", "Luvnith Sisodia", "30 Lakh"),

        # Lucknow Super Giants (LSG)
        ("Lucknow Super Giants", "Nicholas Pooran", "21 Cr"),
        ("Lucknow Super Giants", "Ravi Bishnoi", "11 Cr"),
        ("Lucknow Super Giants", "Mayank Yadav", "11 Cr"),
        ("Lucknow Super Giants", "Ayush Badoni", "4 Cr"),
        ("Lucknow Super Giants", "Mohsin Khan", "4 Cr"),
        ("Lucknow Super Giants", "Rishabh Pant", "27 Cr"),
        ("Lucknow Super Giants", "Avesh Khan", "9.75 Cr"),
        ("Lucknow Super Giants", "Akash Deep", "8 Cr"),
        ("Lucknow Super Giants", "David Miller", "7.50 Cr"),
        ("Lucknow Super Giants", "Abdul Samad", "4.20 Cr"),
        ("Lucknow Super Giants", "Mitchell Marsh", "3.40 Cr"),
        ("Lucknow Super Giants", "Shahbaz Ahmed", "2.40 Cr"),
        ("Lucknow Super Giants", "Aiden Markram", "2 Cr"),
        ("Lucknow Super Giants", "M. Siddharth", "75 Lakh"),
        ("Lucknow Super Giants", "Shamar Joseph", "75 Lakh"),
        ("Lucknow Super Giants", "Aryan Juyal", "30 Lakh"),
        ("Lucknow Super Giants", "Himmat Singh", "30 Lakh"),
        ("Lucknow Super Giants", "Arshin Kulkarni", "30 Lakh"),
        ("Lucknow Super Giants", "Rajvardhan Hangargekar", "30 Lakh"),
        ("Lucknow Super Giants", "Digvesh Singh", "30 Lakh"),
        ("Lucknow Super Giants", "Akash Singh", "30 Lakh"),
        ("Lucknow Super Giants", "Prince Yadav", "30 Lakh"),
        ("Lucknow Super Giants", "Yuvraj Singh", "30 Lakh"),
        ("Lucknow Super Giants", "Matthew Breetzke", "75 Lakh"),

        # Mumbai Indians (MI)
        ("Mumbai Indians", "Jasprit Bumrah", "18 Cr"),
        ("Mumbai Indians", "Suryakumar Yadav", "16.35 Cr"),
        ("Mumbai Indians", "Hardik Pandya", "16.35 Cr"),
        ("Mumbai Indians", "Rohit Sharma", "16.30 Cr"),
        ("Mumbai Indians", "Tilak Varma", "8 Cr"),
        ("Mumbai Indians", "Trent Boult", "12.50 Cr"),
        ("Mumbai Indians", "Deepak Chahar", "9.25 Cr"),
        ("Mumbai Indians", "Naman Dhir", "5.25 Cr"),
        ("Mumbai Indians", "Allah Ghazanfar", "4.80 Cr"),
        ("Mumbai Indians", "Will Jacks", "5.25 Cr"),
        ("Mumbai Indians", "Mitchell Santner", "2 Cr"),
        ("Mumbai Indians", "Ryan Rickelton", "1 Cr"),
        ("Mumbai Indians", "Lizaad Williams", "75 Lakh"),
        ("Mumbai Indians", "Reece Topley", "75 Lakh"),
        ("Mumbai Indians", "Robin Minz", "65 Lakh"),
        ("Mumbai Indians", "Karn Sharma", "50 Lakh"),
        ("Mumbai Indians", "Arjun Tendulkar", "30 Lakh"),
        ("Mumbai Indians", "Ashwani Kumar", "30 Lakh"),
        ("Mumbai Indians", "Bevon Jacobs", "30 Lakh"),
        ("Mumbai Indians", "Raj Angad Bawa", "30 Lakh"),
        ("Mumbai Indians", "Shrijith Krishnan", "30 Lakh"),
        ("Mumbai Indians", "V. Satyanarayana Raju", "30 Lakh"),
        ("Mumbai Indians", "Vignesh Puthur", "30 Lakh"),

        # Punjab Kings (PBKS)
        ("Punjab Kings", "Shashank Singh", "5.50 Cr"),
        ("Punjab Kings", "Prabhsimran Singh", "4 Cr"),
        ("Punjab Kings", "Shreyas Iyer", "26.75 Cr"),
        ("Punjab Kings", "Arshdeep Singh", "18 Cr"),
        ("Punjab Kings", "Yuzvendra Chahal", "18 Cr"),
        ("Punjab Kings", "Marcus Stoinis", "11 Cr"),
        ("Punjab Kings", "Glenn Maxwell", "4.20 Cr"),
        ("Punjab Kings", "Nehal Wadhera", "4.20 Cr"),
        ("Punjab Kings", "Marco Jansen", "7 Cr"),
        ("Punjab Kings", "Josh Inglis", "2.60 Cr"),
        ("Punjab Kings", "Azmatullah Omarzai", "2.40 Cr"),
        ("Punjab Kings", "Lockie Ferguson", "2 Cr"),
        ("Punjab Kings", "Vijaykumar Vyshak", "1.80 Cr"),
        ("Punjab Kings", "Yash Thakur", "1.60 Cr"),
        ("Punjab Kings", "Harpreet Brar", "1.50 Cr"),
        ("Punjab Kings", "Aaron Hardie", "1.25 Cr"),
        ("Punjab Kings", "Vishnu Vinod", "95 Lakh"),
        ("Punjab Kings", "Kuldeep Sen", "80 Lakh"),
        ("Punjab Kings", "Xavier Bartlett", "75 Lakh"),
        ("Punjab Kings", "Harnoor Pannu", "30 Lakh"),
        ("Punjab Kings", "Priyansh Arya", "3.80 Cr"),
        ("Punjab Kings", "Musheer Khan", "30 Lakh"),
        ("Punjab Kings", "Suryansh Shedge", "30 Lakh"),
        ("Punjab Kings", "Pravin Dubey", "80 Lakh"),

        # Rajasthan Royals (RR)
        ("Rajasthan Royals", "Sanju Samson", "18 Cr"),
        ("Rajasthan Royals", "Yashasvi Jaiswal", "18 Cr"),
        ("Rajasthan Royals", "Riyan Parag", "14 Cr"),
        ("Rajasthan Royals", "Dhruv Jurel", "14 Cr"),
        ("Rajasthan Royals", "Shimron Hetmyer", "11 Cr"),
        ("Rajasthan Royals", "Sandeep Sharma", "4 Cr"),
        ("Rajasthan Royals", "Jofra Archer", "12.50 Cr"),
        ("Rajasthan Royals", "Tushar Deshpande", "6.50 Cr"),
        ("Rajasthan Royals", "Wanindu Hasaranga", "5.25 Cr"),
        ("Rajasthan Royals", "Maheesh Theekshana", "4.40 Cr"),
        ("Rajasthan Royals", "Nitish Rana", "4.20 Cr"),
        ("Rajasthan Royals", "Fazalhaq Farooqi", "2 Cr"),
        ("Rajasthan Royals", "Kwena Maphaka", "1.50 Cr"),
        ("Rajasthan Royals", "Akash Madhwal", "1.20 Cr"),
        ("Rajasthan Royals", "Vaibhav Suryavanshi", "1.10 Cr"),
        ("Rajasthan Royals", "Shubham Dubey", "80 Lakh"),
        ("Rajasthan Royals", "Yudhvir Singh", "35 Lakh"),
        ("Rajasthan Royals", "Kumar Kartikeya", "30 Lakh"),
        ("Rajasthan Royals", "Kunal Rathore", "30 Lakh"),
        ("Rajasthan Royals", "Ashok Sharma", "30 Lakh"),
        ("Rajasthan Royals", "Kartik Tyagi", "60 Lakh"),

        # Royal Challengers Bengaluru (RCB)
        ("Royal Challengers Bengaluru", "Virat Kohli", "21 Cr"),
        ("Royal Challengers Bengaluru", "Rajat Patidar", "11 Cr"),
        ("Royal Challengers Bengaluru", "Yash Dayal", "5 Cr"),
        ("Royal Challengers Bengaluru", "Josh Hazlewood", "12.50 Cr"),
        ("Royal Challengers Bengaluru", "Phil Salt", "11.50 Cr"),
        ("Royal Challengers Bengaluru", "Jitesh Sharma", "11 Cr"),
        ("Royal Challengers Bengaluru", "Bhuvneshwar Kumar", "10.75 Cr"),
        ("Royal Challengers Bengaluru", "Liam Livingstone", "8.75 Cr"),
        ("Royal Challengers Bengaluru", "Rasikh Dar", "6 Cr"),
        ("Royal Challengers Bengaluru", "Krunal Pandya", "5.75 Cr"),
        ("Royal Challengers Bengaluru", "Suyash Sharma", "2.60 Cr"),
        ("Royal Challengers Bengaluru", "Devdutt Padikkal", "2 Cr"),
        ("Royal Challengers Bengaluru", "Nuwan Thushara", "1.60 Cr"),
        ("Royal Challengers Bengaluru", "Tim David", "3 Cr"),
        ("Royal Challengers Bengaluru", "Romario Shepherd", "1.50 Cr"),
        ("Royal Challengers Bengaluru", "Jacob Bethell", "2.60 Cr"),
        ("Royal Challengers Bengaluru", "Swapnil Singh", "50 Lakh"),
        ("Royal Challengers Bengaluru", "Manoj Bhandage", "30 Lakh"),

        # Sunrisers Hyderabad (SRH)
        ("Sunrisers Hyderabad", "Heinrich Klaasen", "23 Cr"),
        ("Sunrisers Hyderabad", "Pat Cummins", "18 Cr"),
        ("Sunrisers Hyderabad", "Abhishek Sharma", "14 Cr"),
        ("Sunrisers Hyderabad", "Travis Head", "14 Cr"),
        ("Sunrisers Hyderabad", "Nitish Kumar Reddy", "6 Cr"),
        ("Sunrisers Hyderabad", "Ishan Kishan", "11.25 Cr"),
        ("Sunrisers Hyderabad", "Mohammed Shami", "10 Cr"),
        ("Sunrisers Hyderabad", "Harshal Patel", "8 Cr"),
        ("Sunrisers Hyderabad", "Abhinav Manohar", "3.20 Cr"),
        ("Sunrisers Hyderabad", "Rahul Chahar", "3.20 Cr"),
        ("Sunrisers Hyderabad", "Adam Zampa", "2.40 Cr"),
        ("Sunrisers Hyderabad", "Simarjeet Singh", "1.50 Cr"),
        ("Sunrisers Hyderabad", "Brydon Carse", "1 Cr"),
        ("Sunrisers Hyderabad", "Jaydev Unadkat", "1 Cr"),
        ("Sunrisers Hyderabad", "Kamindu Mendis", "75 Lakh"),
        ("Sunrisers Hyderabad", "Zeeshan Ansari", "40 Lakh"),
        ("Sunrisers Hyderabad", "Atharva Taide", "30 Lakh"),
        ("Sunrisers Hyderabad", "Aniket Verma", "30 Lakh"),
        ("Sunrisers Hyderabad", "Sachin Baby", "30 Lakh"),
        ("Sunrisers Hyderabad", "Eshan Malinga", "1.20 Cr"),
        ("Sunrisers Hyderabad", "Smaran Ravichandran", "30 Lakh"),
        ("Sunrisers Hyderabad", "Harsh Dubey", "30 Lakh")
    ]

    df = pd.DataFrame(data, columns=["Team", "Player Name", "Price"])
    df["Year"] = 2025

    # Save to CSV
    output_dir = Path(__file__).parent.parent / 'data'
    output_dir.mkdir(exist_ok=True)
    file_name = output_dir / "IPL_2025_Players_List.csv"
    df.to_csv(file_name, index=False)

    print(f"CSV created: {file_name}")

if __name__ == "__main__":
    main()
